"""Export the badge model to a C header for the ESP32 port: int8 weights with one scale per row
(in flash), the vocabulary, the merge scores and the word list.

    python badge/tools/export_esp32.py badge/tufty/epitaph/assets badge/esp32/epitaph_esp32/model_data.h
"""

import json
import struct
import sys
from pathlib import Path

import numpy as np


def read_badge_model(path: Path) -> tuple[list[int], dict[str, np.ndarray]]:
    """The EPT1 file written by convert_tinyllama.py, with the split q/k rows put back."""
    raw = path.read_bytes()
    if raw[:4] != b"EPT1":
        raise ValueError(f"{path}: not a badge model file")
    cfg = list(struct.unpack("8i", raw[4:36]))
    dim, hidden, layers, heads, kv_heads, vocab, _seq, unshared = cfg
    if unshared:
        raise ValueError("the ESP32 port expects a shared classifier")
    kv_dim = dim * kv_heads // heads
    w = np.frombuffer(raw, dtype="<f4", offset=36)
    at = 0

    def take(*shape: int) -> np.ndarray:
        nonlocal at
        n = int(np.prod(shape))
        out = w[at : at + n].reshape(shape)
        at += n
        return out

    def interleave(even: np.ndarray, odd: np.ndarray) -> np.ndarray:
        out = np.empty((even.shape[0] * 2, even.shape[1]), dtype=np.float32)
        out[0::2], out[1::2] = even, odd
        return out

    m: dict[str, list[np.ndarray] | np.ndarray] = {"emb": take(vocab, dim)}
    names = ["rms_att", "wq", "wk", "wv", "wo", "rms_ffn", "w1", "w2", "w3"]
    per = {n: [] for n in names}
    for _ in range(layers):
        per["rms_att"].append(take(dim))
        per["wq"].append(interleave(take(dim // 2, dim), take(dim // 2, dim)))
        per["wk"].append(interleave(take(kv_dim // 2, dim), take(kv_dim // 2, dim)))
        per["wv"].append(take(kv_dim, dim))
        per["wo"].append(take(dim, dim))
        per["rms_ffn"].append(take(dim))
        per["w1"].append(take(hidden, dim))
        per["w2"].append(take(dim, hidden))
        per["w3"].append(take(hidden, dim))
    m["rms_final"] = take(dim)
    for n in names:
        m[n] = np.stack(per[n])
    return cfg, m  # type: ignore[return-value]


def quantize(a: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Symmetric int8, one scale per row."""
    rows = a.reshape(-1, a.shape[-1])
    scale = np.maximum(np.abs(rows).max(axis=1), 1e-12) / 127.0
    q = np.clip(np.round(rows / scale[:, None]), -127, 127).astype(np.int8)
    return q, scale.astype(np.float32)


def c_array(ctype: str, name: str, values: np.ndarray | list[float] | list[int]) -> str:
    flat = np.asarray(values).ravel()
    fmt = "{:.8e}f" if ctype == "float" else "{}"
    body = ",".join(fmt.format(v) for v in flat)
    return f"static const {ctype} {name}[{len(flat)}] = {{{body}}};\n"


def c_strings(name: str, items: list[str]) -> str:
    def esc(s: str) -> str:
        return "".join(c if 32 <= ord(c) < 127 and c not in '"\\' else f"\\{ord(c):03o}" for c in s)

    body = ",".join(f'"{esc(s)}"' for s in items)
    return f"static const char *const {name}[{len(items)}] = {{{body}}};\n"


def main() -> None:
    assets, out = Path(sys.argv[1]), Path(sys.argv[2])
    cfg, m = read_badge_model(assets / "model.bin")
    dim, hidden, layers, heads, kv_heads, vocab, _seq, _ = cfg
    pieces = json.loads((assets / "vocab.json").read_text())
    scores = json.loads((assets / "scores.json").read_text())
    words = sorted(json.loads((assets / "lexicon.json").read_text()))

    parts = [
        "/* Generated by badge/tools/export_esp32.py: do not edit. */\n#pragma once\n#include <stdint.h>\n",
        f"#define EP_DIM {dim}\n#define EP_HIDDEN {hidden}\n#define EP_LAYERS {layers}\n",
        f"#define EP_HEADS {heads}\n#define EP_KV_HEADS {kv_heads}\n#define EP_VOCAB {vocab}\n",
        f"#define EP_WORDS {len(words)}\n",
    ]
    for name in ("emb", "wq", "wk", "wv", "wo", "w1", "w2", "w3"):
        q, s = quantize(m[name])
        parts.append(c_array("int8_t", f"ep_{name}_q", q))
        parts.append(c_array("float", f"ep_{name}_s", s))
    for name in ("rms_att", "rms_ffn", "rms_final"):
        parts.append(c_array("float", f"ep_{name}", m[name]))
    parts.append(c_strings("ep_pieces", pieces))
    parts.append(c_array("float", "ep_scores", scores))
    parts.append(c_strings("ep_words", words))
    out.write_text("".join(parts))
    weights = sum(m[n].size for n in ("emb", "wq", "wk", "wv", "wo", "w1", "w2", "w3"))
    print(
        f"{out}: {weights} int8 weights, {len(words)} words, {out.stat().st_size // 1024} KB of source"
    )


if __name__ == "__main__":
    main()
